version: "3"
services:
    react-opensearch-template:
        container_name: "react-opensearch-template"
        image: elyspio/react-opensearch-template
        volumes:
            - "./config/front/conf.js:/back/wwwroot/conf.js"
            - "./config/back/appsettings.json:/back/appsettings.json"
        networks:
            - external
            - internal
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.react-opensearch-template-prefix.stripprefix.prefixes=/react-opensearch-template"
            - "traefik.http.routers.react-opensearch-template.middlewares=react-opensearch-template-prefix@docker"
            - "traefik.http.routers.react-opensearch-template.rule=PathPrefix(`/react-opensearch-template`)"
            - "traefik.http.services.react-opensearch-template.loadbalancer.server.port=4000"
            - "traefik.http.routers.react-opensearch-template.entrypoints=external"



networks:
    internal:
        external: true
    external:
        external: true
